Improvements to DAR for RHEL5 and LD_ASSUME_KERNEL handling.

diff --git a/dar-exec b/dar-exec
--- a/dar-exec
+++ b/dar-exec
@@ -2,8 +2,8 @@
 source "/usr/share/dar/dar-functions"
 
 function help {
-	cat <<EOF
-usage: dar-exec [-q] [-d dist,dist2] cmd	
+    cat <<EOF
+usage: dar-exec [-q] [-d dist,dist2] cmd    
 Run a command in one or more DAR build environments
 
 dar-exec options:
@@ -32,8 +32,8 @@ shift $((OPTIND-1))
 CMD=$@
 
 if [ ! -d "$ROOT" ]; then
-	echo "ERROR: probably in chroot jail" >&2
-	exit 1
+    echo "ERROR: probably in chroot jail" >&2
+    exit 1
 fi
 
 set_dists
@@ -41,39 +41,30 @@ set_as_root
 AS_ROOT=1
 
 for distname in $DISTS; do
-	if [ -z "$QUIET" ]; then
-		echo -e "$_BL_$_WH= Executing \"$_YE$CMD$_WH\" for $_YE$distname$_WH.$_DE"
-	fi
+    if [ -z "$QUIET" ]; then
+        echo -e "$_BL_$_WH= Executing \"$_YE$CMD$_WH\" for $_YE$distname$_WH.$_DE"
+    fi
 
-	if [ -r "$CONFIGDIR/dists/$distname/config" ]; then
-		source "$CONFIGDIR/dists/$distname/config"
-		export arch="$DISTARCH" dist="${DISTNAME// *}" nick="$DISTNICK" path="$DISTPATH" repo="$REPO" tag="${DISTTAG// *}"
-	fi
+    if [ -r "$CONFIGDIR/dists/$distname/config" ]; then
+        source "$CONFIGDIR/dists/$distname/config"
+        export arch="$DISTARCH" dist="${DISTNAME// *}" nick="$DISTNICK" path="$DISTPATH" repo="$REPO" tag="${DISTTAG// *}"
+    fi
 
-	### Check for building as user
-	if [ $AS_ROOT -eq 1 ]; then
-#		DO_SU="/bin/su -l -c"
-		if [ "$FORCE_VERBOSE" ]; then
-			DO_SU="/bin/bash -x -s"
-		else
-			DO_SU="/bin/bash -s"
-		fi
-	else
-		if [ "$FORCE_VERBOSE" ]; then
-			DO_SU="/bin/su -lm $BUILD_USER -- /bin/bash -x -s"
-		else
-			DO_SU="/bin/su -lm $BUILD_USER -- /bin/bash -s"
-		fi
-	fi
+    ### Check for building as user
+    if [ $AS_ROOT -eq 1 -a -z "$FORCE_VERBOSE" ]; then
+        echo "$CMD" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login -s
+    elif [ $AS_ROOT -eq 1 -a "$FORCE_VERBOSE" ]; then
+        echo "$CMD" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login -x -s
+    elif [ $AS_ROOT -ne 1 -a -z "$FORCE_VERBOSE" ]; then
+        echo "$CMD" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/su -lm $BUILD_USER -c "/bin/bash --login -s"
+    else
+        echo "$CMD" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/su -lm $BUILD_USER -c "/bin/bash --login -x -s"
+    fi
+    RC=$?
 
-#	echo chroot "$CHROOTDIR/$distname" $DO_SU $CMD
-#	chroot "$CHROOTDIR/$distname" $DO_SU $CMD
-	echo "$CMD" | chroot "$CHROOTDIR/$distname" $DO_SU
-	RC=$?
-
-	if [ $RC -ne 0 ]; then
-		error "$_RE_${_WH}Failed execution (RC=$_YE$RC$_WH)$_DE"
-	fi
+    if [ $RC -ne 0 ]; then
+        error "$_RE_${_WH}Failed execution (RC=$_YE$RC$_WH)$_DE"
+    fi
 done
 
 exit 0
diff --git a/dar-prepare b/dar-prepare
--- a/dar-prepare
+++ b/dar-prepare
@@ -3,38 +3,38 @@
 source "/usr/share/dar/dar-functions"
 
 if [ -z "$DEFAULT_DISTS" -o -z "$ROOT" ]; then
-	echo "ERROR: There's something wrong with your configuration !" >&2
-	exit 1
+    echo "ERROR: There's something wrong with your configuration !" >&2
+    exit 1
 fi
 
 umount /dar/build 2>/dev/null
-mount -o bind /dev/shm /dar/build/
+#mount -o bind /dev/shm /dar/build/
 
 for distname in $DEFAULT_DISTS; do
-	if [ "${DEFAULT_DISTS// */}" != $distname ]; then
-		ln -f $CHROOTDIR/${DEFAULT_DISTS// */}/root/.bash_history $CHROOTDIR/$distname/root/.bash_history
-	fi
+    if [ "${DEFAULT_DISTS// */}" != $distname ]; then
+        ln -f $CHROOTDIR/${DEFAULT_DISTS// */}/root/.bash_history $CHROOTDIR/$distname/root/.bash_history
+    fi
 
-	umount $CHROOTDIR/$distname{/dev/pts,/proc,/sys,/tmp,$ROOT/build,$ROOT/} 2>/dev/null
+    umount $CHROOTDIR/$distname{/dev/pts,/proc,/sys,/tmp,$ROOT/build,$ROOT/} 2>/dev/null
 
-#	rm -rf $CHROOTDIR/$distname{$RPMTMPPATH}/*
-	mkdir -p $CHROOTDIR/$distname/$ROOT/
-	mount -o bind $ROOT $CHROOTDIR/$distname/$ROOT/
+#   rm -rf $CHROOTDIR/$distname{$RPMTMPPATH}/*
+    mkdir -p $CHROOTDIR/$distname/$ROOT/
+    mount -o bind $ROOT $CHROOTDIR/$distname/$ROOT/
 
-	mkdir -p $CHROOTDIR/$distname/proc/
-	mount -t proc proc $CHROOTDIR/$distname/proc/
+    mkdir -p $CHROOTDIR/$distname/proc/
+    mount -t proc proc $CHROOTDIR/$distname/proc/
 
-	mkdir -p $CHROOTDIR/$distname/sys/
-	mount -t sysfs sys $CHROOTDIR/$distname/sys/
+    mkdir -p $CHROOTDIR/$distname/sys/
+    mount -t sysfs sys $CHROOTDIR/$distname/sys/
 
-	mkdir -p $CHROOTDIR/$distname/dev/pts/
-	mount -t devpts devpts $CHROOTDIR/$distname/dev/pts/
+    mkdir -p $CHROOTDIR/$distname/dev/pts/
+    mount -t devpts devpts $CHROOTDIR/$distname/dev/pts/
 
-###	Use this when you want to speed up building :)
-	mkdir -p $CHROOTDIR/$distname/$ROOT/build/
-	mount -o bind /dev/shm $CHROOTDIR/$distname$ROOT/build/
+### Use this when you want to speed up building :)
+#    mkdir -p $CHROOTDIR/$distname/$ROOT/build/
+#    mount -o bind /dev/shm $CHROOTDIR/$distname$ROOT/build/
 
-###	Use thise when using X processes inside chroots
-	mkdir -p $CHROOTDIR/$distname/tmp/
-	mount -o bind /tmp/ $CHROOTDIR/$distname/tmp/
+### Use thise when using X processes inside chroots
+#    mkdir -p $CHROOTDIR/$distname/tmp/
+#    mount -o bind /tmp/ $CHROOTDIR/$distname/tmp/
 done
diff --git a/dar-shell b/dar-shell
--- a/dar-shell
+++ b/dar-shell
@@ -2,8 +2,8 @@
 source "/usr/share/dar/dar-functions"
 
 function help {
-	cat <<EOF
-usage: dar-shell [-q] [-d dist,dist2] cmd     
+    cat <<EOF
+usage: dar-shell [-q] [-v] [-d dist,dist2] cmd
 Acquire a shell in one or more DAR build environments
 
 dar-exec options:
@@ -11,6 +11,7 @@ dar-exec options:
   -d dist,dist2         select build envs
   -h                    this help message
   -q                    be very quiet
+  -v                    more verbose
 
 exported variables:
 
@@ -20,12 +21,12 @@ EOF
 exit 1
 }
 
-daropts "d:hq" $@
+daropts "d:hqv" $@
 CMD="$OPTS"
 
 if [ ! -d "$ROOT" ]; then
-	echo "ERROR: probably in chroot jail" >&2
-	exit 1
+    echo "ERROR: probably in chroot jail" >&2
+    exit 1
 fi
 
 set_dists
@@ -33,19 +34,23 @@ set_as_root
 AS_ROOT=1
 
 if [ -z "$QUIET" ]; then
-	echo -e "$_BL_$_WH= Entering shells.$_DE"
+    echo -e "$_BL_$_WH= Entering shells.$_DE"
 fi
 for distname in $DISTS; do
-	if [ -r "$CONFIGDIR/dists/$distname/config" ]; then
-		source "$CONFIGDIR/dists/$distname/config"
-		export arch="$DISTARCH" dist="${DISTNAME// *}" nick="$DISTNICK" path="$DISTPATH" repo="$REPO" tag="${DISTTAG// *}"
-	fi
+    if [ -r "$CONFIGDIR/dists/$distname/config" ]; then
+        source "$CONFIGDIR/dists/$distname/config"
+        export arch="$DISTARCH" dist="${DISTNAME// *}" nick="$DISTNICK" path="$DISTPATH" repo="$REPO" tag="${DISTTAG// *}"
+    fi
 
-	setarch $DISTARCH chroot $CHROOTDIR/$distname
+    if [ -z "$FORCE_VERBOSE" ]; then
+        setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login
+    else
+        setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login -x
+    fi
 done
 if [ -z "$QUIET" ]; then
-	echo -en "$_BL_$_WH= Returning to parent shell. Press ENTER.$_DE"
-	read a
+    echo -en "$_BL_$_WH= Returning to parent shell. Press ENTER.$_DE"
+    read a
 fi
 
 exit 0
